### Get all contacts
GET https://contacts-api-r6lx.onrender.com/contacts

###

### Get one contact
GET https://contacts-api-r6lx.onrender.com/contacts/69aa4ef6ebdb690f2059b9ff

###

### Create contact
POST https://contacts-api-r6lx.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "User",
  "email": "test@email.com",
  "favoriteColor": "Blue",
  "birthday": "2000-01-01"
}

###

### Update contact
PUT https://contacts-api-r6lx.onrender.com/contacts/69aa4ef6ebdb690f2059b9ff
Content-Type: application/json

{
  "firstName": "Thomas",
  "lastName": "Garcia",
  "email": "updated@email.com",
  "favoriteColor": "Green",
  "birthday": "1998-05-20"
}

###

### Delete contact
DELETE https://contacts-api-r6lx.onrender.com/contacts/69af7fef9a9e5aa771b0b8ee